/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nearme_gamecenter_jnitool_JniTools */

#ifndef _Included_com_nearme_gamecenter_jnitool_JniTools
#define _Included_com_nearme_gamecenter_jnitool_JniTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nearme_gamecenter_jnitool_JniTools
 * Method:    getFileMD5
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nearme_gamecenter_jnitool_JniTools_getFileMD5
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
